# Generated by Django 4.2.5 on 2023-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
